books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BookListView.as_view(), name='index'),
    path('search/', views.search_books, name='search'),
    path('create/', views.create_book, name='create'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='detail'),
    path('update/<int:book_id>/', views.update_book, name='update'),
    path('delete/<int:book_id>/', views.delete_book, name='delete'),
    path('<int:book_id>/review/', views.create_review, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
]

booksite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

books/models.py
from django.db import models
from django.conf import settings


class Book(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_year})'


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'


class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return f'{self.name} by {self.author}'


class Provider(models.Model):
    book = models.OneToOneField(
        Book,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    store = models.CharField(max_length=255, blank=True)
    has_stock = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=6,
                                decimal_places=2,
                                null=True,
                                blank=True)

    def __str__(self):
        return f'{self.store} @ {self.price if self.price else "Não"}'

staticpages/models.py
from django.db import models

# Create your models here.

books/forms.py
from django.forms import ModelForm
from .models import Book, Review, Provider


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = [
            'name',
            'release_year',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            'release_year': 'Data de Lançamento',
            'poster_url': 'URL da Capa',
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }


class ProviderForm(ModelForm):
    class Meta:
        model = Provider
        fields = [
            'store',
            'has_stock',
            'price',
        ]
        labels = {
            'store': 'Onde Comprar',
            'has_stock': 'Fora de Estoque?',
            'price': 'Preço',
        }

books/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.shortcuts import render, get_object_or_404
from .models import Book, Review, List, Provider
from .forms import BookForm, ReviewForm, ProviderForm


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'


class BookListView(generic.ListView):
    model = Book
    template_name = 'books/index.html'


def search_books(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        book_list = Book.objects.filter(name__icontains=search_term)
        context = {"book_list": book_list}
    return render(request, 'books/search.html', context)


def create_book(request):
    if request.method == 'POST':
        book_form = BookForm(request.POST)
        provider_form = ProviderForm(request.POST)
        if book_form.is_valid():
            book = Book(**book_form.cleaned_data)
            book.save()
            if provider_form.is_valid(
            ) and provider_form.cleaned_data['store']:
                provider = Provider(book=book, **provider_form.cleaned_data)
                provider.save()
            return HttpResponseRedirect(
                reverse('books:detail', args=(book.id, )))
    else:
        book_form = BookForm()
        provider_form = ProviderForm()
    context = {'book_form': book_form, 'provider_form': provider_form}
    return render(request, 'books/create.html', context)


def update_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if request.method == "POST":
        form = BookForm(reques.POST)
        if form.is_valid():
            book_name = form.cleaned_data['name']
            book_release_year = form.cleaned_data['release_year']
            book_poster_url = form.cleaned_data['poster_url']
            book.save()
        return HttpResponseRedirect(
            reverse('books:detail', args=(book.id, )))
    else:
        form = BookForm(
            initial={
                'name': book.name,
                'release_year': book.release_year,
                'poster_url': book.poster_url
            })
    context = {'book': book, 'form': form}
    return render(request, 'books/update.html', context)


def delete_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if request.method == "POST":
        book.delete()
        return HttpResponseRedirect(reverse('books:index'))

    context = {'book': book}
    return render(request, 'books/delete.html', context)


def create_review(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = form.cleaned_data['author']
            review_text = form.cleaned_data['text']
            review = Review(author=review_author,
                            text=review_text,
                            book=book)
            review.save()
            return HttpResponseRedirect(
                reverse('books:detail', args=(book_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'book': book}
    return render(request, 'books/review.html', context)


class ListListView(generic.ListView):
    model = List
    template_name = 'books/lists.html'


class ListCreateView(generic.CreateView):
    model = List
    template_name = 'books/create_list.html'
    fields = ['name', 'author', 'books']
    success_url = reverse_lazy('books:lists')

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

books/templates/books/create.html
{% extends 'base.html' %}

{% block title %}
Criar Livro
{% endblock title %}

{% block content %}
<h2>Adicionar Livro</h2>

<form action="{% url 'books:create' %}" method="post">
    {% csrf_token %}
    {{ book_form.as_p }}
    {{ provider_form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

books/templates/books/create_list.html
{% extends 'base.html' %}

{% block title %}
Criar Livro
{% endblock title %}

{% block content %}
<h2>Criar Lista</h2>

<form action="{% url 'books:create-list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

books/templates/books/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'books:delete' book.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o livro "{{ book.name }} ({{ book.release_year }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

<p><a href="{% url 'books:detail' book.id %}">Voltar para a página do livro</a></p>
{% endblock content %}

books/templates/books/detail.html
{% extends 'base.html' %}

{% block title %}
{{ book.name }} ({{ book.release_year }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Livro {{ book.name }} ({{ book.release_year }})</h2>

<section class="dados-de-livro">
    <img src="{{ book.poster_url }}" alt="Capa do livro {{ book.name}}">
    <ul>
        <li>Nome: {{ book.name }}</li>
        <li>Ano de Lançamento: {{ book.release_year }} </li>
        {% if book.provider %}
            <li>Onde Comprar: {{ book.provider.store }} </li>
            {% if book.provider.has_stock %}
                <li>Fora de Estoque </li>
            {% else %}
                <li>Preço: R${{ book.provider.price }} </li>
            {% endif %}
        {% endif %}
        {% if book.list_set.all %}
            <li>Incluso nas listas: {{ book.list_set.all|join:", " }} </li>
        {% endif %}
        <li><a href="{% url 'books:update' book.id %}">Editar</a></li>
        <li><a href="{% url 'books:delete' book.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Resenhas</h3>
    </header>
    <ul>
        {% if book.review_set.all %}
            {% for review in book.review_set.all %}
                <figure>
                    <blockquote>
                        "{{ review.text }}"
                    </blockquote>
                    <figcaption>—{{ review.author }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma resenha para este livro.</p>
        {% endif %}
    </ul>
    
    <hr>

    <a href="{% url 'books:review' book.id %}"><button>Crie sua Resenha</button></a>
</section>

{% endblock content %}

books/templates/books/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Livros</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'books:search' %}">Buscar Livros</a></p>
    <p>Não encontrou o livro? <a href="{% url 'books:create' %}">Adicionar Novo Livro</a></p>
</section>
{% if book_list %}
<section class="lista-de-cards">
    {% for book in book_list %}
    <article class="card">
        <a href="{% url 'books:detail' book.id %}"><img src="{{ book.poster_url }}"
                alt="Capa do livro {{ book.name}}"></a>
        <p>{{ book.name }} ({{ book.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum livro.</p>
{% endif %}

{% endblock content %}

books/templates/books/lists.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Listas de Livros</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{list.name}} (de {{ list.author }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for book in list.books.all %}
            <div class="card">
                <a href="{% url 'books:detail' book.id %}"><img src="{{ book.poster_url }}"
                        alt="Capa do Livro {{ book.name}}"></a>
                <p>{{ book.name }} ({{ book.release_year }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'books:create-list' %}"><button>Crie sua Lista</button></a>
</section>

{% endblock content %}

books/templates/books/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhar Livro {{ book.name }} ({{ book.release_year }})</h2>

<form action="{% url 'books:review' book.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'books:detail' book.id %}">Voltar para a página do livro</a></p>
{% endblock content %}

books/templates/books/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Livros por Nome</h2>
<form action="{% url 'books:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if book_list %}
<section class="lista-de-cards">
    {% for book in book_list %}
    <article class="card">
        <img src="{{ book.poster_url }}" alt="Capa do livro {{ book.name}}">
        <p>{{ book.name }} ({{ book.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum livro para a busca.</p>
{% endif %}

{% endblock content %}

books/templates/books/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Livro {{ book.name }} ({{ book.release_year}})</h2>
<form method="POST" action="{% url 'books:update' book.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

<p><a href="{% url 'books:detail' book.id %}">Voltar para a página do livro</a></p>
{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Read that Book!</i></h1>
<p>A Página para Comunidade Resenhadora de Livros</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Read that Book!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.png' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'books:index' %}">Livros</a></li>
                <li><a href="{% url 'books:lists' %}">Listas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>